---
# tasks file for web

- name: install git
  yum:
    name: git
    state: present

- name: checkout lameapp
  git:
    repo: https://github.com/jsmartin/lameapp.git
    version: {{ lameapp_version|string }}

- name: set permissions on app
  file:
    name: /var/www/lameapp/lameapp.py
    mode: 0755

- name: add apache config file
  copy:
    src: lameapp.conf
    dest: {{ sites_available }}
  notify: restart apache

- name: link app conf
  file:
    src: {{ sites_available }}/lameapp.conf
    dest: {{ sites_enabled }}/lameapp.conf
    state: link

- meta: flush_handlers

- name: check for proper resp
  uri:
    url: http://localhost/lame
    return_content: yes
  register: result
  until: '"Hello Moon" in result.content'