---
- name: apply common config on all hosts
  hosts: all
  remote_user: vagrant
  become: yes

  role:
  - common

- name: apply apache and web roles
  hosts: webservers
  remote_user: vagrant
  become: yes

  roles:
  - apache
  - web