# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
 config.vm.box = "hashicorp/precise64"
  
 config.vm.network "forwarded_port", guest: 80, host: 8080
 config.vm.hostname = "custom-machine"
 config.vm.synced_folder "local_folder", "/user"
  
 config.vm.provider "virtualbox" do |v|
 v.gui = true
 v.name = "vagrant-machine"
 v.memory = 1024
 v.cpus = 2
 end
  
end