---
- name: install and start apache
  hosts: webservers
  remote_user: vagrant
  become: yes

  tasks:
    - name: install epel repo
      yum:
        name: epel-release
        state: present

    - name: install python bindings for selinux
      yum:
        name: { { item } }
        state: present
        with_items:
          - libselinux-python
          - libsemanage-python

    - name: is selinux running
      command: getenforce
      register: sestatus
      changed_when: false

    - name: install apache
      yum:
        name: httpd
        state: present

    - name: start apache
      service:
        name: httpd
        state: started
        enabled: yes
